name: not_whatsapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  # firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  shared_preferences: ^2.2.2 
  cloud_firestore: ^4.12.0
  permission_handler: ^11.0.1
  google_sign_in: ^6.1.5
  file_picker: ^6.0.0
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.4
  flutter_svg: ^2.0.9
  story_view: ^0.15.0
  intl: ^0.18.1
  emoji_picker_flutter: ^1.6.3
  grouped_list: ^5.1.2
  path_drawing: ^1.0.1
  dotted_border: ^2.1.0
  
    # overlay_support: latest_version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
