name: not_whatsapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_core: ^2.18.0
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
    # overlay_support: latest_version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
<<<<<<< HEAD

asset:
  asset/  
=======
  assets:
    - assets/
>>>>>>> 37fa6edb5f2a5f366c5162123a02dca2a859457b
